openapi: 3.0.0
info:
  title: TMF620 Product Catalog Management API
  description: API for managing product catalog, including categories, events, and export jobs.
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /categories:
    get:
      summary: Get all categories
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
    post:
      summary: Create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Category created
  /events:
    get:
      summary: Get all events
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
      responses:
        '201':
          description: Event created
  /export:
    post:
      summary: Export job
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                format:
                  type: string
      responses:
        '202':
          description: Export job initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
                  status:
                    type: string
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Event:
      type: object
      properties:
        id:
          type: string
        type:
          type: string